name: Palo Alto Firewalls NetDevOps

on:
  push:
    branches:
    - main
    paths:
      - 'global/acl_entries_to_apply.csv'

jobs:
  panos_update:

    runs-on: ubuntu-20.04

    steps:  
    
    - name: Update ACLs on Palo Alto Firewalls
      run: |
        curl --location --request POST 'https://controller.apps.mford-cluster.mford.io/api/v2/workflow_job_templates/17/launch/' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic ${{ secrets.CONTROLLER_BASIC_AUTH }}'
      shell: bash